### ISSUE TITLE
The results of the whitebox, subtree method

### ISSUE THREAD

**Issue by RuoyuChen10** [stresearch/xfr#7]
Thanks for your work, it seems that it has work after change the demo, however, the original results in the paper as:

![](https://gitee.com/Ruoyu_Chen/images/raw/master/img//test_whitebox_weighted_subtree_ebp_topk_64_mask_nose-1.jpg)

However, after the demo change the results as:

![](https://gitee.com/Ruoyu_Chen/images/raw/master/img//test_whitebox_weighted_subtree_ebp_topk_64_mask_nose.jpg)

The model's parameters is not change, why the result is changed? If there still bugs in the paper?

Looking forward to your reply.

**Comment by jebyrne** [comment]
Hi, the difference is here.

https://github.com/stresearch/xfr/blob/master/demo/test_whitebox.py#L191-L192

The paper uses a scale factor to downweight the individual components when they are visualized, so that stronger components are more red and weaker components are more blue, here:

https://github.com/stresearch/xfr/blob/master/demo/test_whitebox.py#L191

This scale factor is quite sensitive to small variations in the pipeline, and can result in difficult to visualize differences from component to component.  The change disables the scale factor and sets them all to a constant which equalizes the visualization of each component without changing the row-wise order.   

You can re-enable the EBP scale factor by uncommenting line 191 and commenting line 192, which will result in a plot closer to the published result:

https://github.com/stresearch/xfr/blob/master/demo/test_whitebox.py#L192

However, precisely reproducing the results in the paper depends on subtle variations in your pytorch pipeline (e.g. non-determinism in pytorch), which is not expected to be exactly reproducible.
